# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f012fee49963af4440622828d5bd1521154f866e4c43a13516aff77a8db1631f9c0f6043a6242482e21d19c8086fd6a1d2237caf9c157f979892dac6ea0f7ee8

test:
  secret_key_base: ab899ffbb6cedc12c4cdeff824126191814c76626cb702d352f57faf4c300e09c8cae835dccead8d8e10d52ef5a596d4d644fe441072690e380dc936ea1b7422

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
